dtl = [
	{
		id:	0,
		name:	'Mohd. Ali',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'FALSE',
		_gender:	'',
	},
	{
		id:	1,
		name:	'K M Salim',
		mobile:	'9846377865',
		status1:	'Administrative Assistant',
		status2:	'Medical Dept.',
		dob:	'',
		link:	'0',
		_alive:	'TRUE',
		_gender:	'',
	},
	{
		id:	2,
		name:	'K K Zahida',
		mobile:	'9895732071',
		status1:	'Principal',
		status2:	'Higher Secondary Dept.',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	3,
		name:	'Sarin K Salim',
		mobile:	'9895504760',
		status1:	'B.Tech',
		status2:	'Computer Science',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	4,
		name:	'Sachin K Salim',
		mobile:	'8281285234',
		status1:	'B.Tech',
		status2:	'Computer Science',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	5,
		name:	'K K Beerachi',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'11',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	6,
		name:	'Mohd. Nazar',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	7,
		name:	'Soudabi',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	8,
		name:	'Aishabi',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	9,
		name:	'Mohd. Iqbal',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	10,
		name:	'Mohd. Sageer',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	11,
		name:	'K B',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	12,
		name:	'Aishu',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	13,
		name:	'K K Kunjumoitheen',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	14,
		name:	'K K Kunjipokkar kutti',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	15,
		name:	'K K Fathima',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	16,
		name:	'K K Kamaal',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	17,
		name:	'K K Aathu',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	18,
		name:	'K K Suharabi',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
	{
		id:	19,
		name:	'K K Zaheed',
		mobile:	'-',
		status1:	'',
		status2:	'',
		dob:	'',
		link:	'',
		_alive:	'',
		_gender:	'',
	},
];